// <auto-generated />
using System;
using LolStatsTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LolStatsTracker.API.Migrations
{
    [DbContext(typeof(MatchDbContext))]
    partial class MatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LolStatsTracker.Shared.Models.MatchEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Champion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentDivision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyBot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnemySupport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameLengthMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LpChange")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Support")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Win")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LolStatsTracker.Shared.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("LolStatsTracker.Shared.Models.MatchEntry", b =>
                {
                    b.HasOne("LolStatsTracker.Shared.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
