// <auto-generated />
using System;
using LolStatsTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LolStatsTracker.API.Migrations
{
    [DbContext(typeof(MatchDbContext))]
    partial class MatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LolStatsTracker.Shared.Models.MatchEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int?>("Augment1")
                        .HasColumnType("integer");

                    b.Property<int?>("Augment2")
                        .HasColumnType("integer");

                    b.Property<int?>("Augment3")
                        .HasColumnType("integer");

                    b.Property<int?>("Augment4")
                        .HasColumnType("integer");

                    b.Property<string>("Champion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ChampionLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("CombatPlayerScore")
                        .HasColumnType("integer");

                    b.Property<int>("Cs")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentDivision")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLp")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<int?>("DamageSelfMitigated")
                        .HasColumnType("integer");

                    b.Property<int?>("DamageShieldedOnTeammates")
                        .HasColumnType("integer");

                    b.Property<int?>("DamageToBuildings")
                        .HasColumnType("integer");

                    b.Property<int?>("DamageToObjectives")
                        .HasColumnType("integer");

                    b.Property<int?>("DamageToTurrets")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int?>("DoubleKills")
                        .HasColumnType("integer");

                    b.Property<bool?>("FirstBloodAssist")
                        .HasColumnType("boolean");

                    b.Property<bool?>("FirstBloodKill")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GameEndedInEarlySurrender")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GameEndedInSurrender")
                        .HasColumnType("boolean");

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("GameLengthMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GoldEarned")
                        .HasColumnType("integer");

                    b.Property<int?>("GoldSpent")
                        .HasColumnType("integer");

                    b.Property<int?>("HealOnTeammates")
                        .HasColumnType("integer");

                    b.Property<int?>("InhibitorsKilled")
                        .HasColumnType("integer");

                    b.Property<string>("ItemsBuild")
                        .HasColumnType("text");

                    b.Property<int?>("KillingSprees")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<string>("LaneAlly")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LaneEnemy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LaneEnemyAlly")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LargestCriticalStrike")
                        .HasColumnType("integer");

                    b.Property<int?>("LargestKillingSpree")
                        .HasColumnType("integer");

                    b.Property<int?>("LargestMultiKill")
                        .HasColumnType("integer");

                    b.Property<int?>("LongestTimeSpentLiving")
                        .HasColumnType("integer");

                    b.Property<int?>("MagicDamageDealt")
                        .HasColumnType("integer");

                    b.Property<int?>("MagicDamageTaken")
                        .HasColumnType("integer");

                    b.Property<int?>("MagicDamageToChampions")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("PentaKills")
                        .HasColumnType("integer");

                    b.Property<int?>("PerkPrimaryStyle")
                        .HasColumnType("integer");

                    b.Property<int?>("PerkSubStyle")
                        .HasColumnType("integer");

                    b.Property<string>("Perks")
                        .HasColumnType("text");

                    b.Property<int?>("PhysicalDamageDealt")
                        .HasColumnType("integer");

                    b.Property<int?>("PhysicalDamageTaken")
                        .HasColumnType("integer");

                    b.Property<int?>("PhysicalDamageToChampions")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int?>("QuadraKills")
                        .HasColumnType("integer");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Spell1Casts")
                        .HasColumnType("integer");

                    b.Property<int?>("Spell1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Spell2Casts")
                        .HasColumnType("integer");

                    b.Property<int?>("Spell2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Spell3Casts")
                        .HasColumnType("integer");

                    b.Property<int?>("Spell4Casts")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeCCingOthers")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeSpentDead")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalDamageDealt")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalDamageTaken")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalHeal")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalPlayerScore")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalTimeCCDealt")
                        .HasColumnType("integer");

                    b.Property<int?>("TripleKills")
                        .HasColumnType("integer");

                    b.Property<int?>("TrueDamageDealt")
                        .HasColumnType("integer");

                    b.Property<int?>("TrueDamageTaken")
                        .HasColumnType("integer");

                    b.Property<int?>("TrueDamageToChampions")
                        .HasColumnType("integer");

                    b.Property<int?>("TurretsKilled")
                        .HasColumnType("integer");

                    b.Property<int?>("UnitsHealed")
                        .HasColumnType("integer");

                    b.Property<int?>("VisionScore")
                        .HasColumnType("integer");

                    b.Property<int?>("VisionWardsBought")
                        .HasColumnType("integer");

                    b.Property<int?>("WardsKilled")
                        .HasColumnType("integer");

                    b.Property<int?>("WardsPlaced")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Matches_Date");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("IX_Matches_ProfileId");

                    b.HasIndex("ProfileId", "Champion")
                        .HasDatabaseName("IX_Matches_ProfileId_Champion");

                    b.HasIndex("ProfileId", "Date")
                        .HasDatabaseName("IX_Matches_ProfileId_Date");

                    b.HasIndex("ProfileId", "Role")
                        .HasDatabaseName("IX_Matches_ProfileId_Role");

                    b.HasIndex("ProfileId", "Date", "GameMode")
                        .HasDatabaseName("IX_Matches_ProfileId_Date_GameMode");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LolStatsTracker.Shared.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Number = 15,
                            StartDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LolStatsTracker.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LolStatsTracker.Shared.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("FlexLP")
                        .HasColumnType("integer");

                    b.Property<string>("FlexRank")
                        .HasColumnType("text");

                    b.Property<string>("FlexTier")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("RiotPuuid")
                        .HasColumnType("text");

                    b.Property<int?>("SoloLP")
                        .HasColumnType("integer");

                    b.Property<string>("SoloRank")
                        .HasColumnType("text");

                    b.Property<string>("SoloTier")
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("LolStatsTracker.Shared.Models.MatchEntry", b =>
                {
                    b.HasOne("LolStatsTracker.Shared.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LolStatsTracker.Shared.Models.UserProfile", b =>
                {
                    b.HasOne("LolStatsTracker.Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
