// <auto-generated />
using System;
using LolStatsTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LolStatsTracker.API.Data.Migrations
{
    [DbContext(typeof(MatchDbContext))]
    [Migration("20251202160059_AddRankAndRoles")]
    partial class AddRankAndRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LolStatsTracker.Shared.Models.MatchEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Champion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentDivision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyBot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnemySupport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameLengthMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LpChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Support")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Win")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
